FROM python:3.12-slim

WORKDIR /app

COPY client.py /app/client.py
COPY input.png /app/input.png
RUN pip install --no-cache-dir requests Pillow
CMD ["bash"]

# Dockerfile.locust
FROM python:3.12-slim

WORKDIR /app

COPY locustfile.py /app/locustfile.py
COPY input.png /app/input.png

RUN pip install --no-cache-dir locust requests Pillow

CMD ["locust", "-f", "locustfile.py", "--host=http://localhost:8000"]
